<?php

namespace Database\Seeders;

use App\Models\Employee;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Sample employees for Turks Kebab Restaurant
        $employees = [
            [
                'employee_id' => 'TK001',
                'first_name' => 'Maria',
                'last_name' => 'Rodriguez',
                'nickname' => 'Mari',
                'gender' => 'female',
                'date_of_birth' => Carbon::parse('1985-06-15'),
                'phone_number' => '649-123-4567',
                'email_address' => 'maria.rodriguez@email.com',
                'address' => '123 Grace Bay Road, Providenciales',
                'status' => 'citizen',
                'status_document_type' => 'status_card',
                'status_card_number' => 'TC123456789',
                'nib_number' => 'NIB123456789',
                'nib_deduction' => 8.50,
                'nhib_number' => 'NHIB987654321',
                'nhib_deduction' => 15.25,
                'payment_method' => 'cibc',
                'bank_account_number' => '1234567890',
                'bank_routing_number' => '900000001',
                'starting_date' => Carbon::parse('2020-03-15'),
                'contract_type' => 'hourly',
                'hourly_rate' => 18.50,
                'contract_signed' => true,
                'uniform_size' => 'M',
                'department' => 'foh',
                'position' => 'Server',
                'employment_status' => 'active',
            ],
            [
                'employee_id' => 'TK002',
                'first_name' => 'James',
                'last_name' => 'Smith',
                'nickname' => 'Jimmy',
                'gender' => 'male',
                'date_of_birth' => Carbon::parse('1992-11-22'),
                'phone_number' => '649-234-5678',
                'email_address' => 'james.smith@email.com',
                'address' => '456 Leeward Highway, Providenciales',
                'status' => 'belonger',
                'status_document_type' => 'status_card',
                'status_card_number' => 'BLG234567890',
                'nib_number' => 'NIB234567890',
                'nib_deduction' => 8.50,
                'nhib_number' => 'NHIB876543210',
                'nhib_deduction' => 15.25,
                'payment_method' => 'scotiabank',
                'bank_account_number' => '2345678901',
                'bank_routing_number' => '900000002',
                'starting_date' => Carbon::parse('2021-08-10'),
                'contract_type' => 'hourly',
                'hourly_rate' => 22.00,
                'contract_signed' => true,
                'uniform_size' => 'L',
                'department' => 'boh',
                'position' => 'Line Cook',
                'employment_status' => 'active',
            ],
            [
                'employee_id' => 'TK003',
                'first_name' => 'Sarah',
                'last_name' => 'Johnson',
                'nickname' => null,
                'gender' => 'female',
                'date_of_birth' => Carbon::parse('1988-04-10'),
                'phone_number' => '649-345-6789',
                'email_address' => 'sarah.johnson@email.com',
                'address' => '789 Conch Bar Road, Middle Caicos',
                'status' => 'resident',
                'status_document_type' => 'permanent_resident_certificate',
                'permanent_resident_certificate_number' => 'PRC789456123',
                'nib_number' => 'NIB345678901',
                'nib_deduction' => 8.50,
                'nhib_number' => 'NHIB765432109',
                'nhib_deduction' => 15.25,
                'payment_method' => 'rbc',
                'bank_account_number' => '3456789012',
                'bank_routing_number' => '900000003',
                'starting_date' => Carbon::parse('2019-01-15'),
                'contract_type' => 'salary',
                'salary_amount' => 42000.00,
                'contract_signed' => true,
                'uniform_size' => 'S',
                'department' => 'foh',
                'position' => 'Assistant Manager',
                'employment_status' => 'active',
            ],
            [
                'employee_id' => 'TK004',
                'first_name' => 'Ahmed',
                'last_name' => 'Hassan',
                'nickname' => null,
                'gender' => 'male',
                'date_of_birth' => Carbon::parse('1990-09-05'),
                'phone_number' => '649-456-7890',
                'email_address' => 'ahmed.hassan@email.com',
                'address' => '321 Blue Hills Road, Providenciales',
                'status' => 'work_permit_holder',
                'status_document_type' => 'work_permit',
                'work_permit_card_number' => 'WP2024001234',
                'work_permit_card_expiry' => Carbon::parse('2025-12-31'),
                'payment_method' => 'cibc',
                'bank_account_number' => '4567890123',
                'bank_routing_number' => '900000001',
                'starting_date' => Carbon::parse('2022-05-01'),
                'contract_type' => 'hourly',
                'hourly_rate' => 16.00,
                'contract_signed' => true,
                'uniform_size' => 'M',
                'department' => 'boh',
                'position' => 'Prep Cook',
                'employment_status' => 'active',
            ],
            [
                'employee_id' => 'TK005',
                'first_name' => 'Emily',
                'last_name' => 'Williams',
                'nickname' => 'Em',
                'gender' => 'female',
                'date_of_birth' => Carbon::parse('1995-12-08'),
                'phone_number' => '649-567-8901',
                'email_address' => 'emily.williams@email.com',
                'address' => '654 Turtle Cove Road, Providenciales',
                'status' => 'work_permit_holder',
                'status_document_type' => 'work_permit',
                'work_permit_first_receipt_number' => 'WPR2025001234',
                'work_permit_first_receipt_expiry' => Carbon::parse('2025-02-15'), // Expiring soon
                'payment_method' => 'check',
                'starting_date' => Carbon::parse('2023-10-01'),
                'contract_type' => 'hourly',
                'hourly_rate' => 15.50,
                'contract_signed' => true,
                'uniform_size' => 'S',
                'department' => 'foh',
                'position' => 'Host/Hostess',
                'employment_status' => 'active',
            ],
            [
                'employee_id' => 'TK006',
                'first_name' => 'Michael',
                'last_name' => 'Brown',
                'nickname' => 'Mike',
                'gender' => 'male',
                'date_of_birth' => Carbon::parse('1987-03-20'),
                'phone_number' => '649-678-9012',
                'email_address' => 'michael.brown@email.com',
                'address' => '987 Downtown Road, Cockburn Town',
                'status' => 'citizen',
                'status_document_type' => 'status_card',
                'status_card_number' => 'TC456789012',
                'nib_number' => 'NIB456789012',
                'nib_deduction' => 8.50,
                'nhib_number' => 'NHIB654321098',
                'nhib_deduction' => 15.25,
                'payment_method' => 'scotiabank',
                'bank_account_number' => '5678901234',
                'bank_routing_number' => '900000002',
                'starting_date' => Carbon::parse('2018-06-01'),
                'contract_type' => 'salary',
                'salary_amount' => 65000.00,
                'contract_signed' => true,
                'uniform_size' => 'L',
                'department' => 'foh',
                'position' => 'General Manager',
                'employment_status' => 'active',
            ],
            [
                'employee_id' => 'TK007',
                'first_name' => 'Lisa',
                'last_name' => 'Garcia',
                'nickname' => null,
                'gender' => 'female',
                'date_of_birth' => Carbon::parse('1993-07-14'),
                'phone_number' => '649-789-0123',
                'email_address' => 'lisa.garcia@email.com',
                'address' => '147 Five Cays Road, Providenciales',
                'status' => 'work_permit_holder',
                'status_document_type' => 'work_permit',
                'work_permit_card_number' => 'WP2023001234',
                'work_permit_card_expiry' => Carbon::parse('2024-12-31'), // Already expired
                'payment_method' => 'rbc',
                'bank_account_number' => '6789012345',
                'bank_routing_number' => '900000003',
                'starting_date' => Carbon::parse('2023-01-15'),
                'contract_type' => 'hourly',
                'hourly_rate' => 17.25,
                'contract_signed' => true,
                'uniform_size' => 'M',
                'department' => 'foh',
                'position' => 'Bartender',
                'employment_status' => 'inactive', // Due to expired permit
            ],
            [
                'employee_id' => 'TK008',
                'first_name' => 'David',
                'last_name' => 'Thompson',
                'nickname' => 'Dave',
                'gender' => 'male',
                'date_of_birth' => Carbon::parse('1991-01-25'),
                'phone_number' => '649-890-1234',
                'email_address' => 'david.thompson@email.com',
                'address' => '258 Airport Road, Providenciales',
                'status' => 'belonger',
                'status_document_type' => 'status_card',
                'status_card_number' => 'BLG567890123',
                'nib_number' => 'NIB567890123',
                'nib_deduction' => 8.50,
                'nhib_number' => 'NHIB543210987',
                'nhib_deduction' => 15.25,
                'payment_method' => 'cibc',
                'bank_account_number' => '7890123456',
                'bank_routing_number' => '900000001',
                'starting_date' => Carbon::parse('2020-11-01'),
                'contract_type' => 'hourly',
                'hourly_rate' => 19.75,
                'contract_signed' => true,
                'uniform_size' => 'XL',
                'department' => 'boh',
                'position' => 'Chef',
                'employment_status' => 'active',
            ]
        ];

        foreach ($employees as $employeeData) {
            Employee::create($employeeData);
        }
    }
}
